// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jftcwbtkbxkmypdjqqwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmdGN3YnRrYnhrbXlwZGpxcXdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0OTgxOTYsImV4cCI6MjA5MTA3NDE5Nn0.YnLSPlPM3gdfWLOOuMpnmIkAq_NffZqByCEZXlPxVwk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});